DATETIME_FORMAT:
    date: '%Y-%m-%d'
    datetime: '%Y-%m-%dT%H%M%S'
    time: '%H-%M-%S'
FILESYSTEM_OPTIONS:
    ignore:
    - '*.swp'
    - '*/.*'
    sanitize_filename: true
    sanitize_strict: false
FILETAGS_OPTIONS:
    between_tag_separator: ' '
    filename_tag_separator: ' -- '
NAME_TEMPLATES:
    default_book: '{publisher} {title} {edition} - {author} {datetime}.{extension}'
    default_document: '{title} - {author} {datetime}.{extension}'
    default_photo: '{datetime} {description} -- {tags}.{extension}'
RULES:
    Document Analyzer with UTF-8-demo.txt:
        CONDITIONS:
            extractor.filesystem.xplat.basename.full: 'UTF-8-demo.txt'
            extractor.filesystem.xplat.contents.mime_type: 'text/plain'
        DATA_SOURCES:
            author: analyzer.document.author
            datetime: analyzer.document.datetime
            extension: extractor.filesystem.xplat.contents.mime_type
            title: analyzer.document.datetime
        NAME_TEMPLATE: '{datetime} {title} {author}.{extension}'
        exact_match: true
        ranking_bias: 1
COMPATIBILITY:
    autonameow_version: v0.5.5
